fg2: <main> function()
  block 0: [entry]
    node 0: constant[undefined,v1] (test-resources/src/flowgraphbuilder/flowgraph_builder0205.js)
    ->[block 1]
  block 1:
    node 1: constant["tajs-host-env:string-replace-model.js",v2] (host-environment-sources-loader)
    node 2: constant[true,v3] (host-environment-sources-loader)
    ->[block 2]
  block 2:
    node 3: call[TAJS_load,v2,v3,v4] (host-environment-sources-loader)
    ->[block 3]
  block 3:
    node 4: call[-,v4,-] (host-environment-sources-loader)
    ->[block 4]
  block 4:
    node 5: read-variable['p',-,-]* (test-resources/src/flowgraphbuilder/flowgraph_builder0205.js:2:5)
    ->[block 9] ~>[block 5]
  block 5:
    node 6: catch[e,v5] (test-resources/src/flowgraphbuilder/flowgraph_builder0205.js:3:3)
    node 7: begin-with[v5]* (test-resources/src/flowgraphbuilder/flowgraph_builder0205.js:3:3)
    ->[block 6]
  block 6:
    node 8: read-variable['v',-,v6]* (test-resources/src/flowgraphbuilder/flowgraph_builder0205.js:4:5)
    ->[block 8] ~>[block 7]
  block 7:
    node 9: end-with* (test-resources/src/flowgraphbuilder/flowgraph_builder0205.js:3:3)
    ->[block 10]
  block 8:
    node 10: end-with* (test-resources/src/flowgraphbuilder/flowgraph_builder0205.js:3:3)
    ->[block 9]
  block 9: [exit-ordinary]
    node 11: return[v1] (test-resources/src/flowgraphbuilder/flowgraph_builder0205.js)
    ->[]
  block 10: [exit-exceptional]
    node 12: exceptional-return (test-resources/src/flowgraphbuilder/flowgraph_builder0205.js)
    ->[]

test-resources/src/flowgraphbuilder/flowgraph_builder0205.js: [definite] Ordinary program exit is unreachable
test-resources/src/flowgraphbuilder/flowgraph_builder0205.js:2:5: [definite] ReferenceError, reading absent variable p
test-resources/src/flowgraphbuilder/flowgraph_builder0205.js:4:5: [definite] ReferenceError, reading absent variable v
test-resources/src/flowgraphbuilder/flowgraph_builder0205.js: [maybe] Uncaught exception, constructed at [test-resources/src/flowgraphbuilder/flowgraph_builder0205.js:4:5]
Soundness testing succeeded for 1 checks (with 0 expected failures)
